### ISSUE TITLE
Cancellation of the marking due to a colon

### ISSUE THREAD

**Issue by rouvenjahnke** [juergenbr/obsidian-tolino-notes-import#2]
Hello, I have the following request: When I mark passages with a colon in my eBook: 
<img width="644" alt="image" src="https://github.com/juergenbr/obsidian-tolino-notes-import/assets/141525719/03b18731-2891-43c5-96c8-575c45c94fbe">

 Unfortunately, this is not transferred to Obsidian and the marking is cancelled there: 
<img width="366" alt="image" src="https://github.com/juergenbr/obsidian-tolino-notes-import/assets/141525719/21758a46-6fe0-4bde-a1a1-c904aef48d2b">

**Comment by juergenbr** [comment]
@rpj-07 thanks for reporting this! It should be fixed in the new version 1.1.0, I would appreciate your feedback!

**Comment by rouvenjahnke** [comment]
> @rpj-07 thanks for reporting this! It should be fixed in the new version 1.1.0, I would appreciate your feedback!

Thanks for modify this! Now its working:
![image](https://github.com/juergenbr/obsidian-tolino-notes-import/assets/141525719/7639fc5a-e5ce-49fc-8f70-504839717283)
If it can be edited quickly: After the ":" there must be a space

**Comment by juergenbr** [comment]
@rpj-07 ups sorry, should be fixed now in version 1.1.1

**Comment by rouvenjahnke** [comment]
> @rpj-07 ups sorry, should be fixed now in version 1.1.1

Thank you very much for this Modifikation, its work!
And also fundamental to the creation of this helpful plugin!
