### ISSUE TITLE
No connection to Tolino 6

### ISSUE THREAD

**Issue by rbialoz** [juergenbr/obsidian-tolino-notes-import#5]
Hi Juergen,

I am not able to connect my Tolino 6 to obsidian. When I plug in the tolino into the computer Windows shows just the name "tolino vision 6" but no drive letter. If I connect trough Linux, it uses the mtp-protocol. What would I need to put into the field "Tolino path drive"? Any help?

Thanks
Ronald

**Comment by juergenbr** [comment]
Hi Ronald!
Unfortunately newer Tolino versions switched to using the MTP protocol (https://mytolino.com/faq/im-having-trouble-pairing-my-tolino-ereader-with-my-computer-what-do-i-do/), which means that they do not mount as USB devices. The easiest fix is to manually copy the notes.txt file from Tolino to a directory on your computer and use that as the path in the settings field.

**Comment by rbialoz** [comment]
Thank you. That worked.
